server:
  port:8080

spring:
  datasource:
    username: root
    password: 1
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mappering/*Mapping.xml
  type-aliases-package: com.example.demo.entity